"""
OXHUNTER - jira_github.py
Jira + GitHub Auto Issue Creation
"""

import requests
from typing import Dict, List, Optional

SEVERITY_LABELS = {
    "CRITICAL": ["critical", "security"],
    "HIGH"    : ["high", "security"],
    "MEDIUM"  : ["medium", "security"],
    "LOW"     : ["low", "security"],
    "INFO"    : ["info"],
}


# ─────────────────────────────────────────────
#  GITHUB
# ─────────────────────────────────────────────
class GitHubIntegration:
    def __init__(self, token: str, repo: str):
        """repo = 'owner/repo-name'"""
        self.headers = {"Authorization": f"token {token}",
                        "Accept": "application/vnd.github+json"}
        self.repo    = repo
        self.base    = f"https://api.github.com/repos/{repo}"

    def create_issue(self, finding: Dict) -> Optional[Dict]:
        severity = finding.get("severity", "INFO")
        title    = f"[{severity}] {finding.get('vuln_type','Vulnerability')} — {finding.get('url','')}"
        body     = (
            f"## 🔐 Vulnerability Report\n\n"
            f"| Field | Value |\n|---|---|\n"
            f"| **Type** | {finding.get('vuln_type')} |\n"
            f"| **Severity** | {severity} |\n"
            f"| **URL** | `{finding.get('url')}` |\n"
            f"| **CVSS** | {finding.get('cvss_score', 'N/A')} |\n\n"
            f"### Detail\n{finding.get('detail','N/A')}\n\n"
            f"### Payload\n```\n{finding.get('payload','N/A')}\n```\n\n"
            f"### Remediation\n{finding.get('remediation','N/A')}\n\n"
            "*Generated by OXHUNTER Security Scanner*"
        )
        try:
            r = requests.post(f"{self.base}/issues",
                headers=self.headers,
                json={"title": title, "body": body,
                      "labels": SEVERITY_LABELS.get(severity, [])},
                timeout=10)
            if r.status_code == 201:
                return {"url": r.json().get("html_url"), "number": r.json().get("number")}
        except Exception as e:
            print(f"[!] GitHub error: {e}")
        return None

    def create_bulk(self, findings: List[Dict],
                    min_severity: str = "MEDIUM") -> List[Dict]:
        order    = ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]
        min_i    = order.index(min_severity)
        filtered = [f for f in findings if order.index(f.get("severity","INFO").upper() if f.get("severity","INFO").upper() in order else "INFO") <= min_i]
        results  = []
        for f in filtered:
            issue = self.create_issue(f)
            if issue:
                results.append(issue)
        return results


# ─────────────────────────────────────────────
#  JIRA
# ─────────────────────────────────────────────
class JiraIntegration:
    PRIORITY_MAP = {
        "CRITICAL": "Highest", "HIGH": "High",
        "MEDIUM": "Medium", "LOW": "Low", "INFO": "Lowest"
    }

    def __init__(self, url: str, user: str, token: str, project: str):
        self.base    = url.rstrip("/")
        self.project = project
        self.auth    = (user, token)
        self.headers = {"Content-Type": "application/json"}

    def create_issue(self, finding: Dict) -> Optional[Dict]:
        severity = finding.get("severity", "INFO")
        summary  = f"[{severity}] {finding.get('vuln_type')} — {finding.get('url','')}"
        desc     = (
            f"*Vulnerability Type:* {finding.get('vuln_type')}\n"
            f"*Severity:* {severity}\n"
            f"*URL:* {finding.get('url')}\n"
            f"*CVSS Score:* {finding.get('cvss_score','N/A')}\n\n"
            f"*Detail:*\n{finding.get('detail','N/A')}\n\n"
            f"*Payload:*\n{{code}}{finding.get('payload','N/A')}{{code}}\n\n"
            f"*Remediation:*\n{finding.get('remediation','N/A')}"
        )
        payload = {
            "fields": {
                "project"  : {"key": self.project},
                "summary"  : summary,
                "description": desc,
                "issuetype": {"name": "Bug"},
                "priority" : {"name": self.PRIORITY_MAP.get(severity, "Medium")},
                "labels"   : ["security", "oxhunter", severity.lower()],
            }
        }
        try:
            r = requests.post(f"{self.base}/rest/api/2/issue",
                auth=self.auth, headers=self.headers,
                json=payload, timeout=10)
            if r.status_code == 201:
                data = r.json()
                return {"key": data.get("key"),
                        "url": f"{self.base}/browse/{data.get('key')}"}
        except Exception as e:
            print(f"[!] Jira error: {e}")
        return None

    def create_bulk(self, findings: List[Dict],
                    min_severity: str = "MEDIUM") -> List[Dict]:
        order    = ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]
        min_i    = order.index(min_severity)
        filtered = [f for f in findings if order.index(f.get("severity","INFO").upper() if f.get("severity","INFO").upper() in order else "INFO") <= min_i]
        return [r for f in filtered if (r := self.create_issue(f))]


# ─────────────────────────────────────────────
#  UNIFIED ISSUE MANAGER
# ─────────────────────────────────────────────
class IssueManager:
    def __init__(self, github: Optional[GitHubIntegration] = None,
                 jira: Optional[JiraIntegration] = None):
        self.github = github
        self.jira   = jira

    def create_all(self, findings: List[Dict],
                   min_severity: str = "HIGH") -> Dict:
        results = {"github": [], "jira": []}
        if self.github:
            results["github"] = self.github.create_bulk(findings, min_severity)
        if self.jira:
            results["jira"]   = self.jira.create_bulk(findings, min_severity)
        return results
